---
- name: "Deploy and Start a New VM with Automatic VM ID"
  hosts: localhost
  connection: local
  gather_facts: no

  vars_files:
    - secrets.yml

  vars:
    proxmox_host: "192.168.210.135"
    proxmox_user: "root@pam"
    proxmox_token_id: "demov1"
    proxmox_node: "pve"
    template_vmid: 100
    new_vm_name: "freshbakevm-ubuntu"
  
  tasks:
    - name: "TASK 1: Get latest VM facts from Proxmox"
      community.general.proxmox_facts:
        api_host: "{{ proxmox_host }}"
        api_user: "{{ proxmox_user }}"
        api_token_id: "{{ proxmox_token_id }}"
        api_token_secret: "{{ proxmox_api_secret }}"

    - name: "TASK 2: Calculate the next available VM ID"
      ansible.builtin.set_fact:
        new_vmid: "{{ (proxmox_vms | map(attribute='vmid') | max) + 1 }}"

    # [PERBAIKAN] Tugas kloning dipisah dan hanya untuk membuat VM
    - name: "TASK 3: Clone template {{ template_vmid }} to new VM {{ new_vmid }}"
      community.general.proxmox_kvm:
        api_host: "{{ proxmox_host }}"
        api_user: "{{ proxmox_user }}"
        api_token_id: "{{ proxmox_token_id }}"
        api_token_secret: "{{ proxmox_api_secret }}"
        node: "{{ proxmox_node }}"
        clone: "{{ template_vmid }}"
        vmid: "{{ new_vmid }}"
        name: "{{ new_vm_name }}-{{ new_vmid }}"
        full: yes # Memastikan kloning penuh
        
    # [PERBAIKAN] Tugas baru yang HANYA untuk menyalakan VM
    - name: "TASK 4: Start the newly created VM {{ new_vmid }}"
      community.general.proxmox_kvm:
        api_host: "{{ proxmox_host }}"
        api_user: "{{ proxmox_user }}"
        api_token_id: "{{ proxmox_token_id }}"
        api_token_secret: "{{ proxmox_api_secret }}"
        node: "{{ proxmox_node }}"
        vmid: "{{ new_vmid }}"
        state: started # Tugas ini hanya mengubah status menjadi 'started'