---
- name: "Direct API Clone Test"
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    proxmox_host: "192.168.210.137"
    proxmox_user: "root@pam"
    proxmox_password: "PASSWORD_BARU_ANDA" # <-- Masukkan password sementara di sini
    proxmox_node: "pve"
    template_vmid: 100
    new_vmid: 105
    new_vm_name: "freshbakevm-ubuntu"

  tasks:
    - name: "Attempting to clone VM {{ template_vmid }} via direct API call"
      ansible.builtin.uri:
        url: "https://{{ proxmox_host }}:8006/api2/json/nodes/{{ proxmox_node }}/qemu/{{ template_vmid }}/clone"
        method: POST
        validate_certs: no
        headers:
          # Otentikasi menggunakan tiket Proxmox
          Cookie: "PVEAuthCookie={{ proxmox_ticket.json.data.ticket }}"
          CSRFPreventionToken: "{{ proxmox_ticket.json.data.CSRFPreventionToken }}"
        body_format: json
        body:
          newid: "{{ new_vmid }}"
          name: "{{ new_vm_name }}"
          full: 1 # 1 berarti 'yes' untuk kloning penuh
        status_code: 200 # Harapkan kode sukses
      
      # Ini adalah trik untuk mendapatkan tiket otentikasi terlebih dahulu
      # Blok ini akan dijalankan sebelum task utama karena 'no_log' dan dependensinya
      vars:
        proxmox_ticket: "{{ lookup('url', 'https://' + proxmox_host + ':8006/api2/json/access/ticket', method='post', data={'username': proxmox_user, 'password': proxmox_password}, validate_certs=False) }}"