---
- name: "Deploy and Start a New VM from Proxmox Template"
  hosts: localhost
  connection: local
  gather_facts: no

  vars_files:
    - secrets.yml  # File ini harus berisi proxmox_api_secret

  vars:
    proxmox_host: "192.168.210.135"
    proxmox_user: "root@pam"
    proxmox_token_id: "demov1"
    proxmox_api_secret: "{{ proxmox_api_secret }}"  # Referensi dari secrets.yml
    proxmox_node: "pve"
    template_vmid: 100
    new_vmid: 105
    new_vm_name: "freshbakevm-ubuntu"

  tasks:
    - name: "Clone template {{ template_vmid }} to new VM {{ new_vmid }}"
      community.general.proxmox_kvm:
        api_host: "{{ proxmox_host }}"
        api_user: "{{ proxmox_user }}"
        api_token_id: "{{ proxmox_token_id }}"
        api_token_secret: "{{ proxmox_api_secret }}"  # Sekarang variabel ini terdefinisi
        node: "{{ proxmox_node }}"
        clone: "{{ template_vmid }}"
        vmid: "{{ new_vmid }}"
        name: "{{ new_vm_name }}"

    - name: "Start the newly created VM {{ new_vmid }}"
      community.general.proxmox_kvm:
        api_host: "{{ proxmox_host }}"
        api_user: "{{ proxmox_user }}"
        api_token_id: "{{ proxmox_token_id }}"
        api_token_secret: "{{ proxmox_api_secret }}"  # Sekarang variabel ini terdefinisi
        node: "{{ proxmox_node }}"
        vmid: "{{ new_vmid }}"
        state: started