---
- name: "Deploy and Start a New VM (Efficient Version)"
  hosts: localhost
  connection: local
  gather_facts: no

  vars_files:
    - secrets.yml

  vars:
    proxmox_host: "192.168.210.137"
    proxmox_user: "root@pam"
    proxmox_token_id: "demov2"
    proxmox_node: "pve"
    template_vmid: 100
    new_vmid: 105
    new_vm_name: "freshbakevm-ubuntu"

  tasks:
    - name: "Clone template {{ template_vmid }} to create and start VM {{ new_vmid }}"
      community.general.proxmox_kvm:
        api_host: "{{ proxmox_host }}"
        api_user: "{{ proxmox_user }}"
        api_token_id: "{{ proxmox_token_id }}"
        api_token_secret: "{{ proxmox_api_secret }}"
        node: "{{ proxmox_node }}"
        clone: "{{ template_vmid }}"
        vmid: "{{ new_vmid }}"
        name: "{{ new_vm_name }}"
        state: started # Menggabungkan pembuatan dan start