---
- name: "Deploy and Start a New VM from Proxmox Template"
  hosts: localhost
  connection: local
  gather_facts: no

  # Memuat data rahasia (api_token_secret) dari file terenkripsi
  vars_files:
    - secrets.yml

  # Semua konfigurasi ditempatkan di sini agar mudah diubah
  vars:
    # --- Detail Koneksi Proxmox ---
    proxmox_host: "192.168.210.137"
    proxmox_user: "root@pam"
    proxmox_token_id: "demo" # Token ID Anda
    proxmox_node: "pve"

    # --- Konfigurasi VM Baru ---
    template_name: "UbuntuServTemplate"
    new_vm_name: "freshbakevm-ubuntu"
    target_storage: "local-lvm"
  
  tasks:
    # Hanya butuh satu task untuk membuat dan menyalakan VM
    - name: "Clone template '{{ template_name }}' to create and start VM '{{ new_vm_name }}'"
      community.general.proxmox_kvm:
        api_host: "{{ proxmox_host }}"
        api_user: "{{ proxmox_user }}"
        api_token_id: "{{ proxmox_token_id }}"
        api_token_secret: "{{ proxmox_api_secret }}" # Diambil dari file secrets.yml

        node: "{{ proxmox_node }}"
        clone: "{{ template_name }}"
        name: "{{ new_vm_name }}"
        storage: "{{ target_storage }}"
        
        # Opsi 'state: started' akan otomatis menyalakan VM setelah selesai kloning
        state: started 
        timeout: 500