- name: Proxmox Stuff
  hosts: localhost  # Perbaikan: 'hosts' bukan 'host'
  vars:
    name: ubuntu
    api_user: root@pam
    api_password: 7c749f03-f8ce-4f46-aedb-5a61c301f927
    api_host: 192.168.210.135
  
  tasks:
    - name: Set machine name
      set_fact:  # Perbaikan: set_fact bukan setfact
        machine_name: "freshubuntu"
    
    - name: Clone VM from template
      community.general.proxmox_kvm:  # Pastikan menggunakan modul yang benar
        api_user: "{{ api_user }}"
        api_password: "{{ api_password }}"
        api_host: "{{ api_host }}"
        clone: UbuntuServTemplate
        name: "{{ machine_name }}"
        node: pve
        storage: local-lvm
        format: qcow2
        timeout: 500
    
    - name: Start VM
      community.general.proxmox_kvm:
        api_user: "{{ api_user }}"
        api_password: "{{ api_password }}"
        api_host: "{{ api_host }}"
        name: "{{ machine_name }}"
        node: pve
        state: started