---
- name: "Create New VM from Scratch"
  hosts: localhost
  connection: local
  gather_facts: no

  vars_files:
    - secrets.yml

  vars:
    proxmox_host: "192.168.210.135"
    proxmox_user: "root@pam"
    proxmox_token_id: "demov1"
    proxmox_api_secret: "{{ proxmox_api_secret }}"
    proxmox_node: "pve"
    proxmox_storage: "local-lvm"
    template_vmid: 100
    new_vmid: 101  # Gunakan VMID yang berbeda
    new_vm_name: "freshbakevm-ubuntu"

  tasks:
    - name: "Create new VM"
      community.general.proxmox_kvm:
        api_host: "{{ proxmox_host }}"
        api_user: "{{ proxmox_user }}"
        api_token_id: "{{ proxmox_token_id }}"
        api_token_secret: "{{ proxmox_api_secret }}"
        node: "{{ proxmox_node }}"
        vmid: "{{ new_vmid }}"
        name: "{{ new_vm_name }}"
        memory: 2048
        cores: 2
        sockets: 1
        ostype: "l26"  # Linux 2.6/3.x kernel
        scsi0: "{{ proxmox_storage }}:20,cache=writeback,discard=on"
        net0: "virtio,bridge=vmbr0"
        boot: "c"
        bootdisk: "scsi0"
        state: "present"
      register: vm_created

    - name: "Import disk from template"
      ansible.builtin.shell:
        cmd: "qm importdisk {{ new_vmid }} /var/lib/vz/images/{{ template_vmid }}/vm-{{ template_vmid }}-disk-0.raw {{ proxmox_storage }}"
      environment:
        PM_API_URL: "https://{{ proxmox_host }}:8006/api2/json"
        PM_USER: "{{ proxmox_user }}"
        PM_TOKEN_ID: "{{ proxmox_token_id }}"
        PM_TOKEN_SECRET: "{{ proxmox_api_secret }}"
      when: vm_created.changed
      register: import_result

    - name: "Attach imported disk to VM"
      ansible.builtin.shell:
        cmd: "qm set {{ new_vmid }} --scsi0 {{ proxmox_storage }}:vm-{{ new_vmid }}-disk-0,cache=writeback,discard=on"
      environment:
        PM_API_URL: "https://{{ proxmox_host }}:8006/api2/json"
        PM_USER: "{{ proxmox_user }}"
        PM_TOKEN_ID: "{{ proxmox_token_id }}"
        PM_TOKEN_SECRET: "{{ proxmox_api_secret }}"
      when: import_result.changed
      register: attach_result

    - name: "Start the new VM {{ new_vmid }}"
      community.general.proxmox_kvm:
        api_host: "{{ proxmox_host }}"
        api_user: "{{ proxmox_user }}"
        api_token_id: "{{ proxmox_token_id }}"
        api_token_secret: "{{ proxmox_api_secret }}"
        node: "{{ proxmox_node }}"
        vmid: "{{ new_vmid }}"
        state: started
      when: attach_result.changed