---
- name: "Clone VM with Automatic VM ID"
  hosts: localhost
  connection: local
  gather_facts: no

  vars_files:
    - secrets.yml

  vars:
    proxmox_host: "192.168.210.135"
    proxmox_user: "root@pam"
    proxmox_token_id: "demov1"
    proxmox_api_secret: "{{ proxmox_api_secret }}"
    proxmox_node: "pve"
    template_vmid: 100
    starting_vmid: 900    # Mulai dari ID 900

  tasks:
    - name: "Get list of existing VMs"
      community.general.proxmox_facts:
        api_host: "{{ proxmox_host }}"
        api_user: "{{ proxmox_user }}"
        api_token_id: "{{ proxmox_token_id }}"
        api_token_secret: "{{ proxmox_api_secret }}"
        node: "{{ proxmox_node }}"
      register: proxmox_facts

    - name: "Find next available VM ID"
      set_fact:
        new_vmid: "{{ starting_vmid }}"
      until: new_vmid not in proxmox_facts.proxmox_vms | map(attribute='vmid') | list
      retries: 100
      delay: 0
      loop_control:
        loop_var: unused_var

    - name: "Clone template to new VM {{ new_vmid }}"
      community.general.proxmox_kvm:
        api_host: "{{ proxmox_host }}"
        api_user: "{{ proxmox_user }}"
        api_token_id: "{{ proxmox_token_id }}"
        api_token_secret: "{{ proxmox_api_secret }}"
        node: "{{ proxmox_node }}"
        clone: "{{ template_vmid }}"
        vmid: "{{ new_vmid }}"
        name: "clone-{{ new_vmid }}"
        timeout: 300