---
- name: "Clone Existing VM/Template"
  hosts: localhost
  connection: local
  gather_facts: no

  vars_files:
    - secrets.yml

  vars:
    proxmox_host: "192.168.210.135"
    proxmox_user: "root@pam"
    proxmox_token_id: "demov1"
    proxmox_api_secret: "{{ proxmox_api_secret }}"
    proxmox_node: "pve"
    template_vmid: 100    # ID template yang akan di-clone
    new_vmid: 999         # ✅ Gunakan ID yang tinggi dan belum digunakan
    new_vm_name: "cloned-vm-999"

  tasks:
    - name: "Clone VM/template to new VM"
      community.general.proxmox_kvm:
        api_host: "{{ proxmox_host }}"
        api_user: "{{ proxmox_user }}"
        api_token_id: "{{ proxmox_token_id }}"
        api_token_secret: "{{ proxmox_api_secret }}"
        node: "{{ proxmox_node }}"
        clone: "{{ template_vmid }}"
        vmid: "{{ new_vmid }}"
        name: "{{ new_vm_name }}"
        timeout: 300