---
- name: "Clone VM with Automatic VM ID"
  hosts: localhost
  connection: local
  gather_facts: no

  vars_files:
    - secrets.yml

  vars:
    proxmox_host: "192.168.210.135"
    proxmox_user: "root@pam"
    proxmox_token_id: "demov1"
    proxmox_api_secret: "{{ proxmox_api_secret }}"
    proxmox_node: "pve"
    template_vmid: 100
    starting_vmid: 900

  tasks:
    - name: "Get list of existing VMs using proxmox_kvm"
      community.general.proxmox_kvm:
        api_host: "{{ proxmox_host }}"
        api_user: "{{ proxmox_user }}"
        api_token_id: "{{ proxmox_token_id }}"
        api_token_secret: "{{ proxmox_api_secret }}"
        node: "{{ proxmox_node }}"
        vmid: "{{ template_vmid }}"  # Gunakan VM yang sudah ada
      register: vm_info

    - name: "Debug to see available VM IDs"
      debug:
        msg: "VM info: {{ vm_info }}"

    - name: "Clone template to new VM {{ starting_vmid }}"
      community.general.proxmox_kvm:
        api_host: "{{ proxmox_host }}"
        api_user: "{{ proxmox_user }}"
        api_token_id: "{{ proxmox_token_id }}"
        api_token_secret: "{{ proxmox_api_secret }}"
        node: "{{ proxmox_node }}"
        clone: "{{ template_vmid }}"
        vmid: "{{ starting_vmid }}"
        name: "clone-{{ starting_vmid }}"
        timeout: 300