---
- name: "Clone CT Template by Name"
  hosts: localhost
  connection: local
  gather_facts: no

  vars_files:
    - secrets.yml

  vars:
    proxmox_host: "192.168.210.135"
    proxmox_user: "root@pam"
    proxmox_token_id: "demov1"
    proxmox_api_secret: "{{ proxmox_api_secret }}"
    proxmox_node: "pve"
    template_name: "CTedgeTemplate"  # Nama template
    new_ct_id: 200
    new_ct_name: "cloned-container"
    storage: "local-lvm"

  tasks:
    - name: "Get list of containers to find template ID"
      community.general.proxmox:
        api_host: "{{ proxmox_host }}"
        api_user: "{{ proxmox_user }}"
        api_token_id: "{{ proxmox_token_id }}"
        api_token_secret: "{{ proxmox_api_secret }}"
        node: "{{ proxmox_node }}"
        validate_certs: no
      register: containers_list

    - name: "Find template ID by name"
      set_fact:
        template_id: "{{ item.vmid }}"
      loop: "{{ containers_list.lxc }}"
      when: item.name == template_name
      loop_control:
        label: "{{ item.name }}"

    - name: "Fail if template not found"
      fail:
        msg: "Template '{{ template_name }}' not found on node {{ proxmox_node }}"
      when: template_id is not defined

    - name: "Clone the container template"
      community.general.proxmox:
        api_host: "{{ proxmox_host }}"
        api_user: "{{ proxmox_user }}"
        api_token_id: "{{ proxmox_token_id }}"
        api_token_secret: "{{ proxmox_api_secret }}"
        node: "{{ proxmox_node }}"
        clone: "{{ template_id }}"   # Gunakan ID yang ditemukan
        vmid: "{{ new_ct_id }}"
        hostname: "{{ new_ct_name }}"
        storage: "{{ storage }}"
        full: true
        timeout: 300
      register: clone_result
      when: template_id is defined

    - name: "Start the cloned container"
      community.general.proxmox:
        api_host: "{{ proxmox_host }}"
        api_user: "{{ proxmox_user }}"
        api_token_id: "{{ proxmox_token_id }}"
        api_token_secret: "{{ proxmox_api_secret }}"
        node: "{{ proxmox_node }}"
        vmid: "{{ new_ct_id }}"
        state: started
      when: clone_result.changed

    - name: "Display results"
      debug:
        msg: "CT {{ new_ct_id }} cloned from {{ template_name }} (ID: {{ template_id }})"
      when: clone_result.changed