---
- name: "Clone Existing VM/Template"
  hosts: localhost
  connection: local
  gather_facts: no

  vars_files:
    - secrets.yml

  vars:
    proxmox_host: "192.168.210.135"
    proxmox_user: "root@pam"
    proxmox_token_id: "demov1"
    proxmox_api_secret: "{{ proxmox_api_secret }}"
    proxmox_node: "pve"
    template_vm: UbuntuServTemplate  # ID VM/template yang akan di-clone
    new_vm_name: "cloned-vm"  # Nama untuk VM baru

  tasks:
    - name: "Clone VM/template to new VM"
      community.general.proxmox_kvm:
        api_host: "{{ proxmox_host }}"
        api_user: "{{ proxmox_user }}"
        api_token_id: "{{ proxmox_token_id }}"
        api_token_secret: "{{ proxmox_api_secret }}"
        node: "{{ proxmox_node }}"
        clone: "{{ template_vm }}"  # ID VM/template sumber
        name: "{{ new_vm_name }}"     # Nama untuk VM baru
        storage: local-lvm
        format: qcow2
        full: true                    # Full clone (false untuk linked clone)
        timeout: 500                  # Timeout 5 menit
      register: clone_result

    - name: "Start the cloned VM"
      community.general.proxmox_kvm:
        api_host: "{{ proxmox_host }}"
        api_user: "{{ proxmox_user }}"
        api_token_id: "{{ proxmox_token_id }}"
        api_token_secret: "{{ proxmox_api_secret }}"
        node: "{{ proxmox_node }}"
        name: "{{ new_vm_name }}"
        state: started
      when: clone_result.changed